### ISSUE TITLE
Pass ignoreCache to options

### ISSUE THREAD

**Issue by ricardofbarros** [ahmadnassri/pkg-config#2]
It would be cool to have a feature like this because require will cache the content of the package.json when it's required the first time. 

Instead of relaying always on `require()` you could use `fs` and `JSON.stringify` to read the content of the package.json.

**Comment by ricardofbarros** [comment]
I can do a PR for this.

**Comment by ahmadnassri** [comment]
PR would be great! thanks

**Comment by ahmadnassri** [comment]
relevant: https://nodejs.org/api/globals.html#globals_require_cache

**Comment by ricardofbarros** [comment]
I prefer take the approach of `fs.stat`, `fs.readFileSync` and `JSON.parse` than removing objects from require cache. What do you think? Should I do it via require.cache ?

**Comment by ahmadnassri** [comment]
I'm gonna dig in deep into the require internals to see how it's logic is structured, do you have any good reasoning for doing with `fs` and `JSON.parse`?

**Comment by ricardofbarros** [comment]
Just because I don't find appropriate to mess with require internals, you could end up messing up some stuff the require cached before. Dunno, I just think using fs and JSON.parse would be simpler.
