### ISSUE TITLE
Add object-path support for namespace

### ISSUE THREAD

**Issue by Flet** [ahmadnassri/pkg-config#4]
It would be nice to be able to pass something like:

``` js
// returns `package.repository[url]`
var config = require('pkg-config')('repository.url')
```

This could be done easily with [object-path](https://www.npmjs.com/package/object-path):

``` js
  var objectPath = require('object-path')
  // do we have a custom namespace?
  var config = namespace ? objectPath.get(parent, namespace) : parent
```

Does this make sense to add to this package or handle it on the outside?

**Comment by ahmadnassri** [comment]
while this is useful, I would say this doesn't fit within the scope of `pkg-config`, which is to:

> parse the closest `package.json` and get package specific configuration object

filtering that object, modifying it, writing back to the `package.json` file, or anything else, falls outside this scope ...

**Comment by Flet** [comment]
Cool thanks for the quick response! Great little package too!

**Comment by ahmadnassri** [comment]
@Flet thanks!

if you do end up building a module that does this on top of `pkg-config` or perhaps use a combination of existing packages with `pkg-config` (perhaps in a gist example), let me know and I can add to the docs here!
